Week 2 home work
fizikovnet/t1_academy pull request #2
Opened 2024-09-22 15:22 UTC by fizikovnet

2024-09-23 09:10 UTC, Alexandr056 requested changes
немного корректировок

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .findAny();
.findFirst()
                .orElseThrow();

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +        System.out.println(any.get());
get напрямую - небезопасно, проигнорирован смысл Optional

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .findAny();
.findFirst()
                .orElseThrow();

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +        System.out.println(any.get());
см выше

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .mapToInt(Employee::getAge)
.collect(Collectors.averagingInt(Employee::getAge)); еще как вариант

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .stream()
а вот тут нет, промежуточная коллекция и новый стрим это не корректно

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .sorted()
зачем дважды сортировка?

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .get();
комментарий по Optional выше

2024-09-23 09:10 UTC, Alexandr056 commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .sorted()
.sorted(Comparator.comparing(String :: length, naturalOrder())
                          .thenComparing(naturalOrder()))

2024-09-23 17:52 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .findAny();
fixed

2024-09-23 17:54 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +        System.out.println(any.get());
Ok, бросаю ``RuntimeException::new``, хотя, возможно, это то-же не совсем корректно

2024-09-23 17:54 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .findAny();
fixed

2024-09-23 17:54 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +        System.out.println(any.get());
fixed

2024-09-23 17:55 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .stream()
Да, здесь перемудрил...
fixed

2024-09-23 17:56 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .get();
fixed

2024-09-23 17:56 UTC, fizikovnet commented on src/main/java/com/fizikovnet/hw2/Main.java
> +                .sorted()
fixed

2024-09-24 11:33 UTC, Alexandr056 approved these changes
отлично проделанная работа над ошибками

2024-09-24 11:39 UTC, merged